// VITAR Sport Analytics - Sponsoring Invoices Data
// Generated from Pohoda XML exports

const sponsoringData = [
  {
    "invoice_number": "250100007",
    "order_number": "",
    "date": "2025-01-02",
    "date_due": "2025-01-16",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "",
    "ico": "25566016",
    "email": "Jordan@hokej.zlin.cz;jandova@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-05-01",
    "total_czk": 23801.63,
    "total_czk_bez_dph": 20673.68,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250100553",
    "order_number": "",
    "date": "2025-01-31",
    "date_due": "2025-02-14",
    "company": "OBEC ALBRECHTICE N.O.",
    "customer_name": "",
    "city": "Albrechtice nad Orlicí",
    "zip": "517 22",
    "customer_country": "",
    "ico": "00579106",
    "email": "albrechtice@nadorlici.cz",
    "phone": "725767602",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-02-07",
    "total_czk": 25480.65,
    "total_czk_bez_dph": 22566.95,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250100564",
    "order_number": "",
    "date": "2025-02-03",
    "date_due": "2025-02-17",
    "company": "X-TRAIL RychloHrad,z.s.",
    "customer_name": "",
    "city": "Hradčany",
    "zip": "751 11",
    "customer_country": "",
    "ico": "22716742",
    "email": "",
    "phone": "776708747",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-02-17",
    "total_czk": 5046.66,
    "total_czk_bez_dph": 4505.95,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250100645",
    "order_number": "",
    "date": "2025-02-10",
    "date_due": "2025-02-24",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "",
    "ico": "25566016",
    "email": "Jordan@hokej.zlin.cz;jandova@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-05-01",
    "total_czk": 26874.02,
    "total_czk_bez_dph": 23994.66,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250100688",
    "order_number": "",
    "date": "2025-02-12",
    "date_due": "2025-02-19",
    "company": "Český svaz orientačních sportů",
    "customer_name": "",
    "city": "Praha",
    "zip": "169 00",
    "customer_country": "",
    "ico": "00548677",
    "email": "kuba.skoda@gmail.com;ekonomka@orientacnisporty.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "KPR",
    "channel": "B2B",
    "salesperson": "Karolina",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-02-17",
    "total_czk": 58398.7,
    "total_czk_bez_dph": 51192.91,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250200053",
    "order_number": "",
    "date": "2025-02-13",
    "date_due": "2025-02-27",
    "company": "Telovýchovná jednota BIELA STOPA Kremnica",
    "customer_name": "",
    "city": "Kremnica",
    "zip": "967 01",
    "customer_country": "SK",
    "ico": "35656824",
    "email": "info@bielastopa.eu",
    "phone": "+421911602218",
    "currency": "EUR",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "SK",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-02-20",
    "total_czk": 83033.37,
    "total_czk_bez_dph": 0.0,
    "total_eur": 3311.4,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250100780",
    "order_number": "",
    "date": "2025-02-17",
    "date_due": "2025-03-19",
    "company": "RAUL, s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "110 00",
    "customer_country": "",
    "ico": "25608673",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-03-18",
    "total_czk": 131822.15,
    "total_czk_bez_dph": 117698.35,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250100782",
    "order_number": "",
    "date": "2025-02-17",
    "date_due": "2025-03-03",
    "company": "SK Severka Šumperk, z.s.",
    "customer_name": "",
    "city": "Šumperk",
    "zip": "787 01",
    "customer_country": "",
    "ico": "63696592",
    "email": "",
    "phone": "608208352",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-02-28",
    "total_czk": 30579.22,
    "total_czk_bez_dph": 27075.85,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250100848",
    "order_number": "",
    "date": "2025-02-21",
    "date_due": "2025-03-07",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "",
    "ico": "25566016",
    "email": "Jordan@hokej.zlin.cz;jandova@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-05-01",
    "total_czk": 120610.88,
    "total_czk_bez_dph": 107530.5,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250101228",
    "order_number": "",
    "date": "2025-03-17",
    "date_due": "2025-03-31",
    "company": "Česká paralympijská s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "186 00",
    "customer_country": "",
    "ico": "28249160",
    "email": "rytinova@paralympic.cz",
    "phone": "731444920",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-04-17",
    "total_czk": 6377.08,
    "total_czk_bez_dph": 5693.82,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250101238",
    "order_number": "",
    "date": "2025-03-17",
    "date_due": "2025-04-16",
    "company": "RAUL, s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "110 00",
    "customer_country": "",
    "ico": "25608673",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-04-17",
    "total_czk": 952673.87,
    "total_czk_bez_dph": 837127.63,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102606",
    "order_number": "",
    "date": "2025-05-07",
    "date_due": "2025-05-21",
    "company": "Valaši v pohybu z.s.",
    "customer_name": "",
    "city": "Valašské Meziříčí",
    "zip": "757 01",
    "customer_country": "",
    "ico": "02713667",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 8006.6,
    "total_czk_bez_dph": 7095.72,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102756",
    "order_number": "",
    "date": "2025-05-14",
    "date_due": "2025-05-28",
    "company": "Poutní místo Lomec, z.ú.",
    "customer_name": "",
    "city": "Vodňany",
    "zip": "389 01",
    "customer_country": "",
    "ico": "19468261",
    "email": "",
    "phone": "723144247",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-01",
    "total_czk": 5820.6,
    "total_czk_bez_dph": 5080.98,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102825",
    "order_number": "",
    "date": "2025-05-16",
    "date_due": "2025-05-30",
    "company": "Karásková Erbenová Helena",
    "customer_name": "",
    "city": "Nová Ves nad Nisou",
    "zip": "468 27",
    "customer_country": "",
    "ico": "02009633",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-22",
    "total_czk": 7083.11,
    "total_czk_bez_dph": 6292.72,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102985",
    "order_number": "",
    "date": "2025-05-23",
    "date_due": "2025-06-06",
    "company": "Brněnský klub běžeckých a sportovních aktivit z.s.",
    "customer_name": "",
    "city": "Brno",
    "zip": "602 00",
    "customer_country": "",
    "ico": "22846425",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-31",
    "total_czk": 33235.57,
    "total_czk_bez_dph": 29076.95,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102986",
    "order_number": "",
    "date": "2025-05-23",
    "date_due": "2025-06-06",
    "company": "Brněnský klub běžeckých a sportovních aktivit z.s.",
    "customer_name": "",
    "city": "Brno",
    "zip": "602 00",
    "customer_country": "",
    "ico": "22846425",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-31",
    "total_czk": 38408.27,
    "total_czk_bez_dph": 33651.65,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102991",
    "order_number": "",
    "date": "2025-05-26",
    "date_due": "2025-06-09",
    "company": "Česká paralympijská s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "186 00",
    "customer_country": "",
    "ico": "28249160",
    "email": "rytinova@paralympic.cz",
    "phone": "731444920",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-07-25",
    "total_czk": 119500.09,
    "total_czk_bez_dph": 106609.58,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103003",
    "order_number": "",
    "date": "2025-05-26",
    "date_due": "2025-06-09",
    "company": "CYKLOFIT LIBEREC MTB TEAM, z.s.",
    "customer_name": "",
    "city": "Liberec",
    "zip": "460 01",
    "customer_country": "",
    "ico": "22751548",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-09-03",
    "total_czk": 100842.47,
    "total_czk_bez_dph": 89422.51,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103098",
    "order_number": "",
    "date": "2025-05-27",
    "date_due": "2025-06-10",
    "company": "Runservice",
    "customer_name": "Jiří Záruba",
    "city": "Jičín",
    "zip": "506 01",
    "customer_country": "",
    "ico": "74370791",
    "email": "",
    "phone": "733473533",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-31",
    "total_czk": 13815.91,
    "total_czk_bez_dph": 12295.86,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103179",
    "order_number": "",
    "date": "2025-05-29",
    "date_due": "2025-06-12",
    "company": "SK FAVORIT Bílina z.s.",
    "customer_name": "",
    "city": "Bílina",
    "zip": "418 01",
    "customer_country": "",
    "ico": "49086791",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-22",
    "total_czk": 31231.4,
    "total_czk_bez_dph": 27805.63,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103349",
    "order_number": "",
    "date": "2025-06-04",
    "date_due": "2025-06-18",
    "company": "Pakli sport klub, z. s.",
    "customer_name": "",
    "city": "Jablonné v Podještědí",
    "zip": "471 25",
    "customer_country": "",
    "ico": "70226130",
    "email": "paklisport@paklisport.cz",
    "phone": "774466994",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-07-15",
    "total_czk": 115973.53,
    "total_czk_bez_dph": 102897.55,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103350",
    "order_number": "",
    "date": "2025-06-04",
    "date_due": "2025-06-18",
    "company": "Sportovní klub Rusava, z.s.",
    "customer_name": "",
    "city": "Rusava",
    "zip": "768 41",
    "customer_country": "",
    "ico": "46998161",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 24585.05,
    "total_czk_bez_dph": 21926.44,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103359",
    "order_number": "",
    "date": "2025-06-04",
    "date_due": "2025-07-04",
    "company": "Mgr. Jan Krabec",
    "customer_name": "",
    "city": "Stříbro",
    "zip": "349 01",
    "customer_country": "",
    "ico": "68749431",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "KPR",
    "channel": "B2B",
    "salesperson": "Karolina",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-07-01",
    "total_czk": 3465.44,
    "total_czk_bez_dph": 3045.44,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103386",
    "order_number": "",
    "date": "2025-06-05",
    "date_due": "2025-06-12",
    "company": "Stanislav Opočenský",
    "customer_name": "",
    "city": "Trutnov",
    "zip": "541 01",
    "customer_country": "",
    "ico": "11113740",
    "email": "opoca@seznam.cz",
    "phone": "724203700",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-01",
    "total_czk": 31025.64,
    "total_czk_bez_dph": 27150.3,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103471",
    "order_number": "",
    "date": "2025-06-09",
    "date_due": "2025-06-23",
    "company": "Obec Kobylí",
    "customer_name": "",
    "city": "Kobylí",
    "zip": "691 10",
    "customer_country": "",
    "ico": "00283266",
    "email": "maslova.jana@enervit.cz",
    "phone": "739695426",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-31",
    "total_czk": 22810.29,
    "total_czk_bez_dph": 20167.44,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250103925",
    "order_number": "",
    "date": "2025-06-25",
    "date_due": "2025-07-02",
    "company": "Český svaz orientačních sportů",
    "customer_name": "",
    "city": "Praha",
    "zip": "169 00",
    "customer_country": "",
    "ico": "00548677",
    "email": "kuba.skoda@gmail.com;ekonomka@orientacnisporty.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "KPR",
    "channel": "B2B",
    "salesperson": "Karolina",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-06-25",
    "total_czk": 13510.98,
    "total_czk_bez_dph": 11798.2,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250104245",
    "order_number": "",
    "date": "2025-07-10",
    "date_due": "2025-07-24",
    "company": "Česká paralympijská s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "186 00",
    "customer_country": "",
    "ico": "28249160",
    "email": "rytinova@paralympic.cz",
    "phone": "731444920",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-07-25",
    "total_czk": 17916.26,
    "total_czk_bez_dph": 15996.66,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250104266",
    "order_number": "",
    "date": "2025-07-11",
    "date_due": "2025-07-25",
    "company": "Spartak Žebrák, z.s.",
    "customer_name": "",
    "city": "Žebrák",
    "zip": "267 53",
    "customer_country": "",
    "ico": "45083649",
    "email": "",
    "phone": "724370472",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-01",
    "total_czk": 15732.93,
    "total_czk_bez_dph": 13833.02,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250104335",
    "order_number": "",
    "date": "2025-07-14",
    "date_due": "2025-07-28",
    "company": "Lucie Šnebergerová",
    "customer_name": "",
    "city": "Rokycany 1",
    "zip": "337 01",
    "customer_country": "",
    "ico": "06839584",
    "email": "maslova.jana@enervit.cz",
    "phone": "775105152",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 13670.29,
    "total_czk_bez_dph": 12205.6,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250104500",
    "order_number": "",
    "date": "2025-07-21",
    "date_due": "2025-08-04",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "CZ",
    "ico": "25566016",
    "email": "Jordan@hokej.zlin.cz;jandova@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 52857.0,
    "total_czk_bez_dph": 47193.74,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250104559",
    "order_number": "",
    "date": "2025-07-23",
    "date_due": "2025-08-06",
    "company": "MORAVA FLOW, z.s.",
    "customer_name": "",
    "city": "Olomouc",
    "zip": "779 00",
    "customer_country": "",
    "ico": "19424892",
    "email": "kuba@moravaflow.cz;maslova.jana@enervit.cz",
    "phone": "728083531",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 6755.49,
    "total_czk_bez_dph": 5899.1,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250104972",
    "order_number": "",
    "date": "2025-08-08",
    "date_due": "2025-08-22",
    "company": "DP sport s.r.o.",
    "customer_name": "",
    "city": "Železné",
    "zip": "666 01",
    "customer_country": "",
    "ico": "19625235",
    "email": "polasek.daniel@vitar.cz;maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 3824.03,
    "total_czk_bez_dph": 3414.31,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250200584",
    "order_number": "",
    "date": "2025-08-18",
    "date_due": "2025-09-01",
    "company": "TENTS s.r.o.",
    "customer_name": "",
    "city": "Žilina",
    "zip": "010 01",
    "customer_country": "SK",
    "ico": "51141884",
    "email": "sneznickymaraton@gmail.com;maslova.jana@enervit.cz",
    "phone": "+421903638547",
    "currency": "EUR",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "SK",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-30",
    "total_czk": 24641.32,
    "total_czk_bez_dph": 0.0,
    "total_eur": 1006.59,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105181",
    "order_number": "",
    "date": "2025-08-18",
    "date_due": "2025-09-01",
    "company": "BB Sport s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "120 00",
    "customer_country": "",
    "ico": "28540174",
    "email": "maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-27",
    "total_czk": 20529.62,
    "total_czk_bez_dph": 18053.1,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105275",
    "order_number": "",
    "date": "2025-08-20",
    "date_due": "2025-09-03",
    "company": "Jiskra Vír, z.s.",
    "customer_name": "",
    "city": "Vír",
    "zip": "592 66",
    "customer_country": "",
    "ico": "48895156",
    "email": "petrstyndl@seznam.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-01",
    "total_czk": 1869.31,
    "total_czk_bez_dph": 1618.0,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105373",
    "order_number": "",
    "date": "2025-08-25",
    "date_due": "2025-09-08",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "CZ",
    "ico": "25566016",
    "email": "Jordan@hokej.zlin.cz;jandova@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 4759.0,
    "total_czk_bez_dph": 4249.11,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105421",
    "order_number": "",
    "date": "2025-08-26",
    "date_due": "2025-09-09",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "CZ",
    "ico": "25566016",
    "email": "Jordan@hokej.zlin.cz;jandova@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 2530.0,
    "total_czk_bez_dph": 2258.93,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105461",
    "order_number": "",
    "date": "2025-08-27",
    "date_due": "2025-09-10",
    "company": "Brněnský klub běžeckých a sportovních aktivit z.s.",
    "customer_name": "",
    "city": "Brno",
    "zip": "602 00",
    "customer_country": "",
    "ico": "22846425",
    "email": "petr.bozek@triexpert.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-31",
    "total_czk": 23567.96,
    "total_czk_bez_dph": 20363.84,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105482",
    "order_number": "",
    "date": "2025-08-28",
    "date_due": "2025-09-11",
    "company": "Sportovní klub DDsport, z. s.",
    "customer_name": "",
    "city": "Vrbátky",
    "zip": "798 12",
    "customer_country": "",
    "ico": "22841474",
    "email": "maslova.jana@enervit.cz;info@4drun.cz",
    "phone": "777615685",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-31",
    "total_czk": 6755.5,
    "total_czk_bez_dph": 5899.11,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105744",
    "order_number": "",
    "date": "2025-09-08",
    "date_due": "2025-09-22",
    "company": "SPORTOVNÍ KLUB SLAVIA PRAHA - BASKETBAL, a.s.",
    "customer_name": "",
    "city": "Praha",
    "zip": "100 00",
    "customer_country": "CZ",
    "ico": "21054835",
    "email": "bruncajsthecoach@gmail.com; david.dousa@raul.cz",
    "phone": "778958823",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-12",
    "total_czk": 129942.0,
    "total_czk_bez_dph": 116019.65,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250105788",
    "order_number": "",
    "date": "2025-09-09",
    "date_due": "2025-09-23",
    "company": "Prague Games Club z.s.",
    "customer_name": "",
    "city": "Praha",
    "zip": "162 00",
    "customer_country": "",
    "ico": "26619695",
    "email": "",
    "phone": "777306043",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-01",
    "total_czk": 160622.95,
    "total_czk_bez_dph": 142450.25,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106080",
    "order_number": "",
    "date": "2025-09-18",
    "date_due": "2025-10-02",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "CZ",
    "ico": "25566016",
    "email": "Jordan@hokej.zlin.cz;jandova@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 66603.0,
    "total_czk_bez_dph": 59466.96,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106464",
    "order_number": "",
    "date": "2025-10-06",
    "date_due": "2025-10-20",
    "company": "Tělocvičná jednota Sokol Stupno",
    "customer_name": "",
    "city": "Břasy",
    "zip": "338 24",
    "customer_country": "",
    "ico": "47695757",
    "email": "maslova.jana@enervit.cz",
    "phone": "737417912",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-01",
    "total_czk": 14040.0,
    "total_czk_bez_dph": 11603.32,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106489",
    "order_number": "",
    "date": "2025-10-07",
    "date_due": "2025-10-21",
    "company": "Česká paralympijská s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "186 00",
    "customer_country": "",
    "ico": "28249160",
    "email": "maslova.jana@enervit.cz",
    "phone": "731444920",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-27",
    "total_czk": 54448.67,
    "total_czk_bez_dph": 48520.04,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106687",
    "order_number": "",
    "date": "2025-10-21",
    "date_due": "2025-11-04",
    "company": "Mgr. Soňa Hrabec Kotulková",
    "customer_name": "",
    "city": "Praha",
    "zip": "152 00",
    "customer_country": "",
    "ico": "06921434",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 5249.99,
    "total_czk_bez_dph": 4338.84,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250200745",
    "order_number": "",
    "date": "2025-10-23",
    "date_due": "2025-11-06",
    "company": "Telovýchovná jednota BIELA STOPA Kremnica",
    "customer_name": "",
    "city": "Kremnica",
    "zip": "967 01",
    "customer_country": "SK",
    "ico": "35656824",
    "email": "info@bielastopa.eu;maslova.jana@enervit.cz",
    "phone": "+421911602218",
    "currency": "EUR",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "SK",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-01",
    "total_czk": 18625.53,
    "total_czk_bez_dph": 0.0,
    "total_eur": 766.01,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106738",
    "order_number": "",
    "date": "2025-10-24",
    "date_due": "2025-11-23",
    "company": "RAUL, s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "110 00",
    "customer_country": "",
    "ico": "25608673",
    "email": "maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-04",
    "total_czk": 470453.12,
    "total_czk_bez_dph": 415823.4,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106739",
    "order_number": "",
    "date": "2025-10-24",
    "date_due": "2025-11-23",
    "company": "RAUL, s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "110 00",
    "customer_country": "",
    "ico": "25608673",
    "email": "maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-24",
    "total_czk": 30655.18,
    "total_czk_bez_dph": 27370.69,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106740",
    "order_number": "",
    "date": "2025-10-24",
    "date_due": "2025-11-23",
    "company": "RAUL, s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "110 00",
    "customer_country": "",
    "ico": "25608673",
    "email": "maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-24",
    "total_czk": 2834.93,
    "total_czk_bez_dph": 2524.49,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106743",
    "order_number": "",
    "date": "2025-10-27",
    "date_due": "2025-11-26",
    "company": "Mgr. Jan Krabec",
    "customer_name": "",
    "city": "Stříbro",
    "zip": "349 01",
    "customer_country": "",
    "ico": "68749431",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "KPR",
    "channel": "B2B",
    "salesperson": "Karolina",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-31",
    "total_czk": 18542.07,
    "total_czk_bez_dph": 16429.5,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106821",
    "order_number": "",
    "date": "2025-11-03",
    "date_due": "2025-11-17",
    "company": "DálRunDál z.s.",
    "customer_name": "",
    "city": "Brno",
    "zip": "615 00",
    "customer_country": "",
    "ico": "17400830",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-18",
    "total_czk": 58551.02,
    "total_czk_bez_dph": 51641.35,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106840",
    "order_number": "",
    "date": "2025-11-04",
    "date_due": "2025-11-18",
    "company": "3THX sportovní klub, spolek",
    "customer_name": "",
    "city": "Dolní Životice",
    "zip": "747 55",
    "customer_country": "",
    "ico": "01221922",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-25",
    "total_czk": 60805.88,
    "total_czk_bez_dph": 53633.53,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106841",
    "order_number": "",
    "date": "2025-11-04",
    "date_due": "2025-11-18",
    "company": "X-TRAIL RychloHrad,z.s.",
    "customer_name": "",
    "city": "Hradčany",
    "zip": "751 11",
    "customer_country": "",
    "ico": "22716742",
    "email": "maslova.jana@vitarsport.cz",
    "phone": "776708747",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 33663.99,
    "total_czk_bez_dph": 30057.13,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106873",
    "order_number": "",
    "date": "2025-11-06",
    "date_due": "2025-11-20",
    "company": "Prague Games Club z.s.",
    "customer_name": "",
    "city": "Praha",
    "zip": "162 00",
    "customer_country": "",
    "ico": "26619695",
    "email": "",
    "phone": "777306043",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-11",
    "total_czk": 12496.65,
    "total_czk_bez_dph": 11157.73,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106876",
    "order_number": "",
    "date": "2025-11-06",
    "date_due": "2025-11-20",
    "company": "Brněnský klub běžeckých a sportovních aktivit z.s.",
    "customer_name": "",
    "city": "Brno",
    "zip": "602 00",
    "customer_country": "",
    "ico": "22846425",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-13",
    "total_czk": 118410.95,
    "total_czk_bez_dph": 104378.24,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106887",
    "order_number": "",
    "date": "2025-11-07",
    "date_due": "2025-11-21",
    "company": "X-TRAIL RychloHrad,z.s.",
    "customer_name": "",
    "city": "Hradčany",
    "zip": "751 11",
    "customer_country": "",
    "ico": "22716742",
    "email": "maslova.jana@vitarsport.cz",
    "phone": "776708747",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-14",
    "total_czk": 3433.27,
    "total_czk_bez_dph": 3065.42,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250200766",
    "order_number": "",
    "date": "2025-11-07",
    "date_due": "2025-11-21",
    "company": "Žilinský pedál",
    "customer_name": "",
    "city": "Žilina",
    "zip": "010 08",
    "customer_country": "SK",
    "ico": "42391075",
    "email": "maslova.jana@vitarsport.cz",
    "phone": "+421948777670",
    "currency": "EUR",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "SK",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-18",
    "total_czk": 79055.12,
    "total_czk_bez_dph": 0.0,
    "total_eur": 3247.94,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106922",
    "order_number": "",
    "date": "2025-11-10",
    "date_due": "2025-11-24",
    "company": "Sportovní klub Rusava, z.s.",
    "customer_name": "",
    "city": "Rusava",
    "zip": "768 41",
    "customer_country": "",
    "ico": "46998161",
    "email": "maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-11",
    "total_czk": 1032.62,
    "total_czk_bez_dph": 921.99,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106923",
    "order_number": "",
    "date": "2025-11-10",
    "date_due": "2025-11-24",
    "company": "Sportovní klub Rusava, z.s.",
    "customer_name": "",
    "city": "Rusava",
    "zip": "768 41",
    "customer_country": "",
    "ico": "46998161",
    "email": "maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Příkazem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-11",
    "total_czk": 1216.82,
    "total_czk_bez_dph": 1086.45,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106924",
    "order_number": "",
    "date": "2025-11-10",
    "date_due": "2025-11-24",
    "company": "UnArt Provodov, p.s.",
    "customer_name": "",
    "city": "Provodov",
    "zip": "763 45",
    "customer_country": "",
    "ico": "75046351",
    "email": "maslova.jana@enervit.cz",
    "phone": "775292611",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-10",
    "total_czk": 10769.64,
    "total_czk_bez_dph": 9562.71,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250106965",
    "order_number": "",
    "date": "2025-11-12",
    "date_due": "2025-11-26",
    "company": "Berani Zlín, s.r.o.",
    "customer_name": "",
    "city": "Zlín",
    "zip": "760 01",
    "customer_country": "CZ",
    "ico": "25566016",
    "email": "krizko@beranizlin.cz",
    "phone": "773900344",
    "currency": "CZK",
    "centre": "JGO",
    "channel": "B2B",
    "salesperson": "Jirka",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 19036.0,
    "total_czk_bez_dph": 16996.43,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250200775",
    "order_number": "",
    "date": "2025-11-14",
    "date_due": "2025-11-28",
    "company": "Realiz Team s.r.o.",
    "customer_name": "",
    "city": "Bratislava",
    "zip": "841 05",
    "customer_country": "SK",
    "ico": "36857581",
    "email": "maslova.jana@enervit.cz",
    "phone": "+421903729777",
    "currency": "EUR",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "SK",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-11-27",
    "total_czk": 16925.26,
    "total_czk_bez_dph": 0.0,
    "total_eur": 699.68,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250107207",
    "order_number": "",
    "date": "2025-11-25",
    "date_due": "2025-12-09",
    "company": "Option Gaudeo s.r.o.",
    "customer_name": "",
    "city": "Brno",
    "zip": "628 00",
    "customer_country": "",
    "ico": "01719653",
    "email": "maslova.jana@enervit.cz",
    "phone": "777643792",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 11210.18,
    "total_czk_bez_dph": 10001.19,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250107209",
    "order_number": "",
    "date": "2025-11-25",
    "date_due": "2025-12-09",
    "company": "JIZERSKÁ, o.p.s.",
    "customer_name": "",
    "city": "Bedřichov",
    "zip": "468 12",
    "customer_country": "",
    "ico": "25412949",
    "email": "maslova.jana@enervit.cz",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": false,
    "liquidation_date": "",
    "total_czk": 35519.06,
    "total_czk_bez_dph": 31650.49,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250101688",
    "order_number": "",
    "date": "2025-04-07",
    "date_due": "2025-04-21",
    "company": "DNK Media s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "102 00",
    "customer_country": "",
    "ico": "06719902",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-04-25",
    "total_czk": 12298.46,
    "total_czk_bez_dph": 10980.77,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250101795",
    "order_number": "",
    "date": "2025-04-10",
    "date_due": "2025-04-24",
    "company": "Oldřich Bujnoch",
    "customer_name": "",
    "city": "Chrudim",
    "zip": "537 05",
    "customer_country": "",
    "ico": "10479724",
    "email": "",
    "phone": "602490127",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-04-10",
    "total_czk": 43790.12,
    "total_czk_bez_dph": 39019.63,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250101817",
    "order_number": "",
    "date": "2025-04-11",
    "date_due": "2025-04-25",
    "company": "Česká paralympijská s.r.o.",
    "customer_name": "",
    "city": "Praha",
    "zip": "186 00",
    "customer_country": "",
    "ico": "28249160",
    "email": "rytinova@paralympic.cz",
    "phone": "731444920",
    "currency": "CZK",
    "centre": "",
    "channel": "B2B",
    "salesperson": "VITAR Sport",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-04-17",
    "total_czk": 25961.87,
    "total_czk_bez_dph": 23180.24,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102263",
    "order_number": "",
    "date": "2025-04-24",
    "date_due": "2025-05-08",
    "company": "Jiří Král",
    "customer_name": "",
    "city": "Most",
    "zip": "434 01",
    "customer_country": "",
    "ico": "21086443",
    "email": "jirka.kral2000@gmail.com",
    "phone": "730905468",
    "currency": "CZK",
    "centre": "KPR",
    "channel": "B2B",
    "salesperson": "Karolina",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-05-28",
    "total_czk": 2424.96,
    "total_czk_bez_dph": 2146.1,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  },
  {
    "invoice_number": "250102444",
    "order_number": "",
    "date": "2025-04-30",
    "date_due": "2025-05-14",
    "company": "Karásková Erbenová Helena",
    "customer_name": "",
    "city": "Nová Ves nad Nisou",
    "zip": "468 27",
    "customer_country": "",
    "ico": "02009633",
    "email": "",
    "phone": "",
    "currency": "CZK",
    "centre": "JMA",
    "channel": "B2B",
    "salesperson": "Štěpán",
    "country": "CZ",
    "supplier": "VITAR",
    "payment_type": "Zápočtem",
    "price_level": "Sponzoring",
    "is_paid": true,
    "liquidation_date": "2025-10-22",
    "total_czk": 10647.8,
    "total_czk_bez_dph": 9507.0,
    "total_eur": 0.0,
    "total_eur_bez_dph": 0.0
  }
];
